// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAswB3tqVpaDJdwbLpmczjJlrt0LENLHso',
    appId: '1:24320835329:web:5f9071de653660ab7c6500',
    messagingSenderId: '24320835329',
    projectId: 'fox-app-e9b9f',
    authDomain: 'fox-app-e9b9f.firebaseapp.com',
    storageBucket: 'fox-app-e9b9f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUToMIV471RlaB7YfWVTaSYCKsrqq0NQk',
    appId: '1:24320835329:android:5ce2f181c813f5d47c6500',
    messagingSenderId: '24320835329',
    projectId: 'fox-app-e9b9f',
    storageBucket: 'fox-app-e9b9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0ZfXLi_mCXdDdOKMRT8WcwfS1A-p3qX8',
    appId: '1:24320835329:ios:6eeee5134f8963987c6500',
    messagingSenderId: '24320835329',
    projectId: 'fox-app-e9b9f',
    storageBucket: 'fox-app-e9b9f.appspot.com',
    androidClientId: '24320835329-k3psga6vmo2rsbbtqh0p1nluc1l491ls.apps.googleusercontent.com',
    iosClientId: '24320835329-3nulk87ooi2bip1edpinvkt5gfcqo7cu.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditFox',
  );

}
